title: soma0sd # 페이지 타이틀
url: "" # 홈페이지 주소
baseurl: "" # 하위페이지일 경우 추가경로 E.g. "/blog"

social:
  email: soma0sd@gmail.com
  github: soma0sd
  facebook: soma0sd
  webpage: https://soma0sd.com

# Build settings
timezone: Asia/Seoul
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _scss
